language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
- travis_retry composer self-update
- "composer require codeclimate/php-test-reporter --dev"
- composer install
script: 
- "phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml"
