language: php

php:
  -'5.4.37'
  -'5.5.21'
  -'5.6.5'
  -'7.1'
  -hhvm

before_install: 
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script: 
- "phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml"

